openapi: 3.0.3
info:
  title: User Service API
  version: 1.0.0
  description: API del microservicio de usuarios

servers:
  - url: http://localhost:8082/api/user

security:
  - bearerAuth: [ ]

tags:
  - name: Users
  - name: Reports
  - name: Fees

components:

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:

    # =======================
    # ENUMS
    # =======================
    AccountType:
      type: string
      enum:
        - BASIC
        - PREMIUM

    AccountState:
      type: string
      enum:
        - ENABLED
        - DISABLED

    ScooterState:
      type: string
      enum:
        - ACTIVE
        - INACTIVE
        - MAINTENANCE

    # =======================
    # MODELOS DEL DOMINIO
    # =======================
    Fee:
      type: object
      properties:
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        pricePerHour:
          type: number
          format: float
        extraHourFee:
          type: number
          format: float
      required:
        - startDate
        - endDate
        - pricePerHour
        - extraHourFee

    Scooter:
      type: object
      properties:
        scooterId:
          type: integer
          format: int64
        kilometers:
          type: number
          format: float
        pause:
          type: integer
        trips:
          type: integer
        latitude:
          type: number
        longitude:
          type: number
        state:
          $ref: "#/components/schemas/ScooterState"

    Trip:
      type: object
      properties:
        scooterId:
          type: integer
        totalKilometers:
          type: number
        totalPausesMinutes:
          type: integer
        totalTrips:
          type: integer

    # =======================
    # REQUEST DTOs
    # =======================
    UserRequestDTO:
      type: object
      properties:
        role:
          type: string
        name:
          type: string
        password:
          type: string
        lastName:
          type: string
        email:
          type: string
        phone:
          type: integer

    PromptRequestDTO:
      type: object
      properties:
        message:
          type: string
      required:
        - message

    # =======================
    # RESPONSE DTOs
    # =======================
    UserResponseDTO:
      type: object
      properties:
        userId:
          type: integer
        role:
          type: string
        name:
          type: string
        lastName:
          type: string
        email:
          type: string
        phone:
          type: integer

    AuthUserResponseDTO:
      type: object
      properties:
        userId:
          type: integer
        email:
          type: string
        role:
          type: string
        password:
          type: string

    ReportADTO:
      type: object
      properties:
        scooterId:
          type: integer
        kilometers:
          type: integer
        pause:
          type: integer

    CancelAccountDTO:
      type: object
      properties:
        accountId:
          type: integer
        accountName:
          type: string
        state:
          $ref: "#/components/schemas/AccountState"

    ReportScooterByYearDTO:
      type: object
      properties:
        scooterId:
          type: integer
        year:
          type: integer
        totalTrips:
          type: integer

    InvoiceReportDTO:
      type: object
      properties:
        totalInvoiced:
          type: number
        totalTrips:
          type: integer

    UserScooterUsageResponseDTO:
      type: object
      properties:
        userId:
          type: integer
        totalScooterUsage:
          type: integer
        monthStart:
          type: integer
        monthEnd:
          type: integer
        accountType:
          $ref: "#/components/schemas/AccountType"

    UserScooterPeriodUsageDTO:
      type: object
      properties:
        userId:
          type: integer
        scooterId:
          type: integer
        uses:
          type: integer
        totalKm:
          type: number

    NearScooterReportDTO:
      type: object
      properties:
        scooterId:
          type: integer
        latitude:
          type: number
        longitude:
          type: number

    FeeResponseDTO:
      type: object
      properties:
        feeId:
          type: string
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        pricePerHour:
          type: number
        extraHourFee:
          type: number

    LLMResponseDTO:
      type: object
      properties:
        llmResponse:
          type: string

paths:

  # =======================
  # CRUD USER
  # =======================

  /:
    post:
      tags: [ Users ]
      summary: Crear un usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRequestDTO"
      responses:
        '201':
          description: Usuario creado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponseDTO"

  /{userId}:
    get:
      tags: [ Users ]
      summary: Obtener usuario por ID
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Usuario encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponseDTO"

    put:
      tags: [ Users ]
      summary: Actualizar usuario
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRequestDTO"
      responses:
        '200':
          description: Usuario actualizado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponseDTO"

    delete:
      tags: [ Users ]
      summary: Eliminar usuario
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Usuario eliminado

  /email/{userEmail}:
    get:
      tags: [ Users ]
      summary: Buscar usuario por email
      parameters:
        - in: path
          name: userEmail
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Datos del usuario
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthUserResponseDTO"

  # =======================
  # REPORTES
  # =======================

  /scooters:
    get:
      tags: [ Reports ]
      summary: Reporte A – Scooters por km
      parameters:
        - in: query
          name: withPause
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: datos extraidos
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReportADTO"

  /toggleState/{accountId}:
    patch:
      tags: [ Reports ]
      summary: Reporte B – Alternar estado de cuenta
      parameters:
        - in: path
          name: accountId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: datos extraidos
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CancelAccountDTO"

  /scooters/usage:
    get:
      tags: [ Reports ]
      summary: Reporte C – Uso de scooters por año
      parameters:
        - in: query
          name: year
          required: true
          schema:
            type: integer
        - in: query
          name: countTrips
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: datos extraidos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ReportScooterByYearDTO"

  /total-invoice:
    get:
      tags: [ Reports ]
      summary: Reporte D – Facturación total
      parameters:
        - in: query
          name: year
          schema: { type: integer }
        - in: query
          name: startMonth
          schema: { type: integer }
        - in: query
          name: endMonth
          schema: { type: integer }
      responses:
        '200':
          description: datos extraidos
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InvoiceReportDTO"

  /scooter-user-usage:
    get:
      tags: [ Reports ]
      summary: Reporte E – Uso de scooters por usuario
      parameters:
        - in: query
          name: monthStart
          schema: { type: integer }
        - in: query
          name: monthEnd
          schema: { type: integer }
        - in: query
          name: userType
          schema:
            $ref: "#/components/schemas/AccountType"
      responses:
        '200':
          description: datos extraidos
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserScooterUsageResponseDTO"

  /fee:
    post:
      tags: [ Fees ]
      summary: Crear tarifa
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Fee"
      responses:
        '201':
          description: tarifa creada
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FeeResponseDTO"


  /near-scooters:
    get:
      tags: [ Reports ]
      summary: Reporte G – Scooters cercanos
      parameters:
        - in: query
          name: latitude
          schema: { type: number }
        - in: query
          name: longitude
          schema: { type: number }
        - in: query
          name: radius
          schema: { type: number }
      responses:
        '200':
          description: datos extraidos
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NearScooterReportDTO"

  /scooter-usages-by-period/{userId}:
    get:
      tags: [ Reports ]
      summary: Reporte H – Uso de scooter por periodo para un usuario
      description: Devuelve los usos del usuario por scooter para un rango de meses del año indicado. Si withRelatedToMyAccount es true, filtra solo los usos relacionados a la cuenta del userId.
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: integer
        - in: query
          name: year
          required: true
          schema:
            type: integer
        - in: query
          name: monthStart
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 12
        - in: query
          name: monthEnd
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 12
        - in: query
          name: withRelatedToMyAccount
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: Lista de usos por periodo
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserScooterPeriodUsageDTO"

  # =======================
  # CHAT / LLM
  # =======================
  /chat:
    post:
      tags: [ Users ]
      summary: Chat con LLM
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PromptRequestDTO"
      responses:
        '200':
          description: datos extraidos
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LLMResponseDTO"

  /historical-data/{userId}:
    post:
      tags: [ Users ]
      summary: Datos históricos (LLM) para un usuario
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PromptRequestDTO"
      responses:
        '200':
          description: datos extraidos
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LLMResponseDTO"

